# Generated by Django 4.2.11 on 2024-07-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_date',
            field=models.DateField(verbose_name='task_date'),
        ),
    ]
