# Generated by Django 4.2.11 on 2024-07-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_tasklist_task_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='tasklist',
            name='monthly_calendar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.monthlycalendar'),
        ),
    ]
