# Generated by Django 4.2.11 on 2024-07-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_tasklist_monthly_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task_amount',
            field=models.IntegerField(default=0),
        ),
    ]
